describe('Fluxo de Vendas - Screenshots', () => {
  
  beforeEach(() => {
    cy.visit('/web/login', { timeout: 60000 })
    cy.wait(2000)
    cy.get('#login', { timeout: 10000 }).clear().type('admin')
    cy.get('#password', { timeout: 10000 }).clear().type('admin')
    cy.get('button[type="submit"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.url().should('not.include', '/web/login')
  })

  it('01 - Tela Inicial Vendas', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(5000)
    cy.screenshot('01-vendas/01-tela-inicial', { capture: 'fullPage' })
  })

  it('02 - Criar Orcamento', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/02-criar-orcamento', { capture: 'fullPage' })
  })

  it('03 - Preencher Cliente', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.screenshot('01-vendas/03-preencher-cliente', { capture: 'fullPage' })
  })

  it('04 - Adicionar Produto', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.screenshot('01-vendas/04-adicionar-produto', { capture: 'fullPage' })
  })

  it('05 - Preencher Produto', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.screenshot('01-vendas/05-preencher-produto', { capture: 'fullPage' })
  })

  it('06 - Confirmar Orcamento', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/06-confirmar-orcamento', { capture: 'fullPage' })
  })

  it('07 - Pedido Confirmado', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/07-pedido-confirmado', { capture: 'fullPage' })
  })

  it('08 - Acessar Transferencia', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_view_delivery"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/08-acessar-transferencia', { capture: 'fullPage' })
  })

  it('09 - Validar Transferencia', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_view_delivery"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="button_validate"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/09-validar-transferencia', { capture: 'fullPage' })
  })

  it('10 - Criar Fatura', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_create_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/10-criar-fatura', { capture: 'fullPage' })
  })

  it('11 - Fatura Criada', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_create_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_view_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/11-fatura-criada', { capture: 'fullPage' })
  })

  it('12 - Confirmar Fatura', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_create_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_view_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_post"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/12-confirmar-fatura', { capture: 'fullPage' })
  })

  it('13 - Registrar Pagamento', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_create_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_view_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_post"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_register_payment"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/13-registrar-pagamento', { capture: 'fullPage' })
  })

  it('14 - Pagamento Confirmado', () => {
    cy.visit('/web#action=sale.action_sale_order', { timeout: 60000 })
    cy.wait(3000)
    cy.get('.o_list_button_add', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('input[name="partner_id"]', { timeout: 10000 }).clear({ force: true }).type('Customer', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('.o_field_x2many_list_row_add a', { timeout: 10000 }).click()
    cy.wait(2000)
    cy.get('.o_selected_row input[name="product_id"]', { timeout: 10000 }).type('Product', { delay: 100 })
    cy.wait(2000)
    cy.get('.ui-autocomplete:visible li', { timeout: 10000 }).first().click()
    cy.wait(2000)
    cy.get('button[name="action_confirm"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_create_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_view_invoice"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_post"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_register_payment"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.get('button[name="action_create_payment"]', { timeout: 10000 }).click()
    cy.wait(3000)
    cy.screenshot('01-vendas/14-pagamento-confirmado', { capture: 'fullPage' })
  })

})
