describe('Fluxo de Vendas - Screenshots', () => {
  
  beforeEach(() => {
    cy.visit('/web/login')
    cy.get('#login').type('admin')
    cy.get('#password').type('admin')
    cy.get('button[type="submit"]').click()
    cy.wait(2000)
  })

  it('01 - Tela Inicial Vendas', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(3000)
    cy.screenshot('01-vendas/01-tela-inicial')
  })

  it('02 - Criar Orcamento', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/02-criar-orcamento')
  })

  it('03 - Preencher Cliente', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.screenshot('01-vendas/03-preencher-cliente')
  })

  it('04 - Adicionar Produto', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.screenshot('01-vendas/04-adicionar-produto')
  })

  it('05 - Preencher Produto', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.screenshot('01-vendas/05-preencher-produto')
  })

  it('06 - Confirmar Orcamento', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/06-confirmar-orcamento')
  })

  it('07 - Pedido Confirmado', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/07-pedido-confirmado')
  })

  it('08 - Acessar Transferencia', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_delivery"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/08-acessar-transferencia')
  })

  it('09 - Validar Transferencia', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_delivery"]').click()
    cy.wait(2000)
    cy.get('button[name="button_validate"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/09-validar-transferencia')
  })

  it('10 - Criar Fatura', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/10-criar-fatura')
  })

  it('11 - Fatura Criada', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_invoice"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/11-fatura-criada')
  })

  it('12 - Confirmar Fatura', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_post"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/12-confirmar-fatura')
  })

  it('13 - Registrar Pagamento', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_post"]').click()
    cy.wait(2000)
    cy.get('button[name="action_register_payment"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/13-registrar-pagamento')
  })

  it('14 - Pagamento Confirmado', () => {
    cy.visit('/web#action=sale.action_sale_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_post"]').click()
    cy.wait(2000)
    cy.get('button[name="action_register_payment"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_payment"]').click()
    cy.wait(2000)
    cy.screenshot('01-vendas/14-pagamento-confirmado')
  })

})
