describe('Fluxo de Compras - Screenshots', () => {
  
  beforeEach(() => {
    cy.visit('/web/login')
    cy.get('#login').type('admin')
    cy.get('#password').type('admin')
    cy.get('button[type="submit"]').click()
    cy.wait(2000)
  })

  it('01 - Tela Inicial Compras', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(3000)
    cy.screenshot('02-compras/01-tela-inicial')
  })

  it('02 - Criar RFQ', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.screenshot('02-compras/02-criar-rfq')
  })

  it('03 - Preencher Fornecedor', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.screenshot('02-compras/03-preencher-fornecedor')
  })

  it('04 - Adicionar Produto', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.screenshot('02-compras/04-adicionar-produto')
  })

  it('05 - Confirmar RFQ', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.screenshot('02-compras/05-confirmar-rfq')
  })

  it('06 - Receber Mercadoria', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_picking"]').click()
    cy.wait(2000)
    cy.screenshot('02-compras/06-receber-mercadoria')
  })

  it('07 - Validar Recebimento', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_picking"]').click()
    cy.wait(2000)
    cy.get('button[name="button_validate"]').click()
    cy.wait(2000)
    cy.screenshot('02-compras/07-validar-recebimento')
  })

  it('08 - Criar Fatura Fornecedor', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.screenshot('02-compras/08-criar-fatura-fornecedor')
  })

  it('09 - Confirmar Fatura', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_post"]').click()
    cy.wait(2000)
    cy.screenshot('02-compras/09-confirmar-fatura')
  })

  it('10 - Pagar Fornecedor', () => {
    cy.visit('/web#action=purchase.action_purchase_order')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Fornecedor', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('button[name="action_confirm"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_view_invoice"]').click()
    cy.wait(2000)
    cy.get('button[name="action_post"]').click()
    cy.wait(2000)
    cy.get('button[name="action_register_payment"]').click()
    cy.wait(2000)
    cy.get('button[name="action_create_payment"]').click()
    cy.wait(2000)
    cy.screenshot('02-compras/10-pagar-fornecedor')
  })

})
