describe('Fluxo de NF-e - Screenshots', () => {
  
  beforeEach(() => {
    cy.visit('/web/login')
    cy.get('#login').type('admin')
    cy.get('#password').type('admin')
    cy.get('button[type="submit"]').click()
    cy.wait(2000)
  })

  it('01 - Tela Inicial Fiscal', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(3000)
    cy.screenshot('04-nfe/01-tela-inicial')
  })

  it('02 - Configuracao Empresa', () => {
    cy.visit('/web#action=base.action_res_company_form')
    cy.wait(3000)
    cy.screenshot('04-nfe/02-configuracao-empresa')
  })

  it('03 - Certificado Digital', () => {
    cy.visit('/web#action=l10n_br_fiscal_certificate.action_certificate')
    cy.wait(3000)
    cy.screenshot('04-nfe/03-certificado-digital')
  })

  it('04 - Operacoes Fiscais', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_operation')
    cy.wait(3000)
    cy.screenshot('04-nfe/04-operacoes-fiscais')
  })

  it('05 - Documento Fiscal', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.screenshot('04-nfe/05-documento-fiscal')
  })

  it('06 - Preencher Documento', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.screenshot('04-nfe/06-preencher-documento')
  })

  it('07 - Adicionar Produto', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.screenshot('04-nfe/07-adicionar-produto')
  })

  it('08 - Impostos Calculados', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.screenshot('04-nfe/08-impostos-calculados')
  })

  it('09 - Enviar NF-e', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_document_confirm"]').click()
    cy.wait(2000)
    cy.screenshot('04-nfe/09-enviar-nfe')
  })

  it('10 - NF-e Autorizada', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_document_confirm"]').click()
    cy.wait(2000)
    cy.screenshot('04-nfe/10-nfe-autorizada')
  })

  it('11 - Imprimir DANFE', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(2000)
    cy.get('button.o_list_button_add').click()
    cy.wait(2000)
    cy.get('div[name="partner_id"] input').type('Cliente', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button.o_button_new').click()
    cy.wait(1000)
    cy.get('div[name="product_id"] input').type('Produto', {delay: 100})
    cy.wait(1000)
    cy.get('.ui-autocomplete li').first().click()
    cy.wait(1000)
    cy.get('button[name="action_document_confirm"]').click()
    cy.wait(2000)
    cy.screenshot('04-nfe/11-imprimir-danfe')
  })

  it('12 - Historico NF-e', () => {
    cy.visit('/web#action=l10n_br_fiscal.action_fiscal_document')
    cy.wait(3000)
    cy.screenshot('04-nfe/12-historico-nfe')
  })

})
